### ISSUE TITLE
EDA UI is blank with latest eda-ui image

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/eda-server-operator#153]
With the latest eda-ui image, the UI shows as blank.  This is because the default url path has changed and the operator's nginx.conf must be updated to reflect this. 

PR here:
* https://github.com/ansible/eda-server-operator/pull/152

**Comment by kurokobo** [comment]
- Related to: https://github.com/ansible/ansible-ui/pull/1266
- Workaround: 
  ```yaml
  image_web: quay.io/ansible/eda-ui
  image_web_version: 2.4.739
  ```
