### ISSUE TITLE
On fresh deployments, sometimes the first reconciliation loop fails on the task "Check for API Pod"

### ISSUE THREAD

**Issue by kurokobo** [ansible/eda-server-operator#154]
#### Description

On fresh deployments for EDA CR, sometimes the first reconciliation loop fails on the task "Check for API Pod".

If we do nothing and wait for the next reconciliation loop, this task will succeed and the deployment will complete.

The first reconciliation:

```bash
...
--------------------------- Ansible Task StdOut -------------------------------
 TASK [Check for API Pod] ******************************** 
fatal: [localhost]: FAILED! => {"api_found": true, "attempts": 3, "changed": false, "resources": []}
...
[eda : Check for API Pod] *************************************************\r\n
task path: /opt/ansible/roles/eda/tasks/deploy_eda.yml:31\n
FAILED - RETRYING: Check for API Pod (3 retries left).\n
FAILED - RETRYING: Check for API Pod (2 retries left).\n
FAILED - RETRYING: Check for API Pod (1 retries left).\n
fatal: [localhost]: FAILED! => {\"api_found\": true, \"attempts\": 3, \"changed\": false, \"resources\": []}\n\r\n
PLAY RECAP *********************************************************************\r\n
localhost                  : ok=53   changed=7    unreachable=0    failed=1    skipped=12   rescued=0    ignored=0   \r\n\n
```

Just wait for the second reconciliation with doing nothing:

```bash
...
TASK [eda : Check for API Pod] *************************************************
task path: /opt/ansible/roles/eda/tasks/deploy_eda.yml:31

-------------------------------------------------------------------------------
{"level":"info","ts":1702472703.452893,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1702472703.856233,"logger":"logging_event_handler","msg":"[playbook task start]","name":"eda","namespace":"eda","gvk":"eda.ansible.com/v1alpha1, Kind=EDA","event_type":"playbook_on_task_start","job":"4939066471100038729","EventData.Name":"eda : Create admin user"}

--------------------------- Ansible Task StdOut -------------------------------

TASK [eda : Create admin user] *************************************************
task path: /opt/ansible/roles/eda/tasks/main.yml:36
```

#### Additional information

This is due to the `until` without `delay` or `retries`.
It wait only for 15 seconds since the default value for `delay` is `5` and `retries` is `3`. 

When pulling image from registry is performed in addition to API initialization for api pod, it often takes tens of seconds or more for the api pod to become ready, making this task very prone to failure.

https://github.com/ansible/eda-server-operator/blob/6df1529acd0b5537aa32470662045d7fdf43ca61/roles/eda/tasks/deploy_eda.yml#L31-L46

We should explicitly specify `delay` and `retries` with enough value (`5` and `24`, 2 minutes in total, for example), or use `wait`, `wait_condition`, `wait_sleep`, and `wait_timeout` for `k8s_info` module instead of `until`: https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_info_module.html

**Comment by rooftopcellist** [comment]
Thank you for reporting this issue and for all of the details!  I have created a PR here to resolve this.  I had it wait for 5 minutes, which is what we do in the awx-operator iirc.  This will give us some buffer time in case there are many migrations introduced by the application in the future that take longer to run. 

* https://github.com/ansible/eda-server-operator/pull/157

@kurokobo please review this when you get a chance, thanks!
