### ISSUE TITLE
DEFAULT_*_VERSION and OPERATOR_VERSION are empty in Operator 1.0.0

### ISSUE THREAD

**Issue by kurokobo** [ansible/eda-server-operator#169]
`make docker-buildx` does not use `BUILD_ARGS`, so even if we specify `BUILD_ARGS` in CI, it will be ignored:

> ```bash
>   BUILD_ARGS="--build-arg DEFAULT_EDA_VERSION=sha-26e62bd \
>       --build-arg DEFAULT_EDA_UI_VERSION=2.4.884 \
>       --build-arg OPERATOR_VERSION=1.0.0" \
>   IMG=ghcr.io/ansible/eda-server-operator:1.0.0 \
>   make docker-buildx
> ```
> https://github.com/ansible/eda-server-operator/actions/runs/7507310771/job/20440601824#step:6:2

Indeed the images for 1.0.0 has empty ENVs:

```bash
$ docker run --rm -it --entrypoint bash quay.io/ansible/eda-server-operator:1.0.0 -c env | sort | grep VERSION
DEFAULT_EDA_UI_VERSION=
DEFAULT_EDA_VERSION=
OPERATOR_VERSION=
TINI_VERSION=v0.19.0

$ docker run --rm -it --entrypoint bash ghcr.io/ansible/eda-server-operator:1.0.0 -c env | sort | grep VERSION
DEFAULT_EDA_UI_VERSION=
DEFAULT_EDA_VERSION=
OPERATOR_VERSION=
TINI_VERSION=v0.19.0
```

@rooftopcellist @jon-nfc 
F.Y.I.😞

**Comment by rooftopcellist** [comment]
Thank you for creating this issue, I have just merged the PR to fix this:
* https://github.com/ansible/eda-server-operator/pull/170

There is now a new 1.0.1 release, which has the correct env vars in the operator image.
* https://github.com/ansible/eda-server-operator/releases/tag/1.0.1

```
$ docker run -it --entrypoint='' quay.io/ansible/eda-server-operator:1.0.1 bash -c "env | grep VERSION"
TINI_VERSION=v0.19.0
OPERATOR_VERSION=1.0.1
DEFAULT_EDA_UI_VERSION=2.4.884
DEFAULT_EDA_VERSION=sha-26e62bd
```
