### ISSUE TITLE
Implement init container for PSQL to avoid permission error on specific implementation of PVs

### ISSUE THREAD

**Issue by kurokobo** [ansible/eda-server-operator#192]
Context:

- https://github.com/ansible/eda-server-operator/pull/122#issuecomment-2049888073
- https://github.com/ansible/awx-operator/pull/1805

@rooftopcellist

**Comment by rooftopcellist** [comment]
Agreed, we should implement this in this operator as well.  That way users won't need to chown the hostPath directory being mounted to PID 26.

**Comment by jamesregis** [comment]
I have made a pull request to fix this issue based on awx-operator : https://github.com/ansible/eda-server-operator/pull/193
